RegenerateTables: false

Db:
  Adapter: postgres
  Conn: postgres://%v:%v@%v/%v?sslmode=disable
  User:
  Password:
  Server: localhost
  Database: star_store

Log:
  Output:
  Level: error
  Format: json